In [22]:
import numpy as np
import pandas as pd
import regex as re

In [2]:
ins = pd.read_csv('inscritos.csv'
                 ,header=1
                 ,sep=',')

In [3]:
colunas=['col1','col2','col3','situacao','nro_inscricao','nome',
        'cpf','data_nascimento','genero','escolaridade',
        'instituicao','telefone','email','cep','bairro',
        'cidade','inclui_outro','perfil','observacao','perfis']

In [4]:
ins.columns=colunas

In [5]:
def columnsDrop():
    ins.drop('situacao', axis=1, inplace=True)
    ins.dropna(axis=1, how='all', inplace=True)
    ins.dropna(axis=0, how='all', inplace=True)

columnsDrop()

In [6]:
ins.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 0 to 30
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   nro_inscricao    31 non-null     float64
 1   nome             31 non-null     object
 2   cpf              31 non-null     object
 3   data_nascimento  31 non-null     object
 4   genero           31 non-null     object
 5   escolaridade     31 non-null     object
 6   instituicao      28 non-null     object
 7   telefone         31 non-null     object
 8   email            31 non-null     object
 9   cep              31 non-null     object
 10  bairro           31 non-null     object
 11  cidade           31 non-null     object
 12  inclui_outro     31 non-null     object
 13  perfil           31 non-null     object
 14  observacao       31 non-null     object
dtypes: float64(1), object(14)
memory usage: 3.9+ KB

In [7]:
def columnsInsert():
    ins.insert(6, 'escolaridade_id',0)
    ins.insert(8, 'instituicao_id',0)
    ins.insert(14, 'cidade_id',0)
    ins.insert(18, 'tamanho_camiseta_id',0)

columnsInsert()

In [14]:
ins.head(3)

,nro_inscricao,nome,cpf,data_nascimento,genero,escolaridade,escolaridade_id,instituicao,instituicao_id,telefone,email,cep,bairro,cidade,cidade_id,inclui_outro,perfil,observacao,tamanho_camiseta_id
0,1.0,Isabelle Victoria Pereira De Souza,51454217880,12/09/2003,Feminino,Ensino Superior,0,Belas Artes,0,11954852961,isabellevictoria.urs@gmail.com,08121-620,Jd Nélia,São Paulo,0,N,Desenvolvedor,Tamanho de Camiseta: M,0
1,2.0,Guilherme Antunes de Campos,50069148821,03/06/2004,Masculino,Ensino Superior Cursando,0,Fatec Guarulhos,0,11959762456,guiancam@gmail.com,7091000,Vila Progresso,Guarulhos,0,N,Desenvolvedor,Tamanho de Camiseta: G,0
2,3.0,Wezilyana Melice Farias de Lima,1264343442,13/08/1983,Feminino,Pós-graduação completo,0,Wyden,0,11992471992,lilyfarias@gmail.com,1529001,Aclimação,São Paulo,0,N,Analista de Negócios,Tamanho de Camiseta: M,0

In [56]:
def cidadeId(cidade):
    if cidade=='Guarulhos':
        return 1
    elif cidade=='São Paulo':
        return 2
    elif cidade=='Ribeirão Preto':
        return 3
    else:
        99

def tamanhoCamiseta(pTamanho) -> int:
    t=re.split('\s',pTamanho)
    if (t[len(t)-1]=='P'):
        return 1
    elif (t[len(t)-1]=='M'):
        return 2
    elif (t[len(t)-1]=='G'):
        return 3
    elif (t[len(t)-1]=='GG'):
        return 4
    else:
        return 5

ins['tamanho_camiseta_id']=ins['observacao'].apply(lambda x: tamanhoCamiseta(x))
ins['cidade_id']=ins['cidade'].apply(lambda x: cidadeId(x))

In [57]:
ins[['cidade','cidade_id','observacao','tamanho_camiseta_id']]

            cidade  cidade_id                observacao  tamanho_camiseta_id
0        São Paulo          2    Tamanho de Camiseta: M                    2
1        Guarulhos          1    Tamanho de Camiseta: G                    3
2        São Paulo          2    Tamanho de Camiseta: M                    2
3        Guarulhos          1    Tamanho de Camiseta: M                    2
4        Guarulhos          1    Tamanho de Camiseta: G                    3
5        Guarulhos          1    Tamanho de Camiseta: G                    3
6   Ribeirão Preto          3    Tamanho de Camiseta: G                    3
7   Ribeirão Preto          3    Tamanho de Camiseta: M                    2
8        Guarulhos          1    Tamanho de Camiseta: M                    2
9        São Paulo          2    Tamanho de Camiseta: M                    2
10       Guarulhos          1    Tamanho de Camiseta: P                    1
11       São Paulo          2   Tamanho de Camiseta: GG                    4
12       São Paulo          2  Tamanho de Camiseta 2: G                    3
13       São Paulo          2  Tamanho de Camiseta 3: G                    3
14       São Paulo          2  Tamanho de Camiseta 3: G                    3
15       São Paulo          2    Tamanho de Camiseta: P                    1
16       Guarulhos          1    Tamanho de Camiseta: P                    1
17       São Paulo          2    Tamanho de Camiseta: G                    3
18       São Paulo          2    Tamanho de Camiseta: P                    1
19       Guarulhos          1    Tamanho de Camiseta: G                    3
20       São Paulo          2    Tamanho de Camiseta: G                    3
21       Guarulhos          1    Tamanho de Camiseta: P                    1
22       São Paulo          2  Tamanho de Camiseta 2: M                    2
23       São Paulo          2   Tamanho de Camiseta: GG                    4
24       São Paulo          2   Tamanho de Camiseta: GG                    4
25       São Paulo          2   Tamanho de Camiseta: GG                    4
26       Guarulhos          1    Tamanho de Camiseta: M                    2
27       Guarulhos          1  Tamanho de Camiseta 2: P                    1
28       Guarulhos          1    Tamanho de Camiseta: M                    2
29       Guarulhos          1  Tamanho de Camiseta 4: M                    2
30       São Paulo          2    Tamanho de Camiseta: M                    2

In [58]:
ins['instituicao'].unique()

array(['Belas Artes', 'Fatec Guarulhos', 'Wyden',
       'Instituto Federal de Educação, Ciência e Tecnologia de São Paulo',
       ' Instituto Federal de Ciência, Tecnologia e Educação de São Paulo',
       'No momento, nenhuma', nan, 'Universidade de São Paulo',
       'Universidade São Judas Tadeu',
       'IFSP instituto federal de São Paulo', 'Usp',
       'Etec Abdias do Nascimento', 'Etec Abdias do nascimento',
       'Centro Universitário Belas Artes de São Paulo',
       'Centro Universitário Eniac', 'Cursando Faculdade', 'FIAP', 'FAM',
       'UNICAMP', 'Liceu de Artes e Ofícios', 'LICEU DE ARTES E OFÍCIOS',
       'Drummond', 'Instituto Federal de São Paulo Campus Guarulhos',
       'Instituto Federal de São Paulo - GRU',
       'E.E Professor Moacyr Campos'], dtype=object)